name: Setup environment
description: Setup environment for the project

inputs:
  node-version:
    description: Node.js version
    default: latest

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
    - run: corepack enable && pnpm install
      shell: bash
